# Generated by Django 5.2.9 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0002_alter_veiculo_placa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
