# Generated by Django 6.0 on 2026-08-24 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_default_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('entidade', models.CharField(choices=[('pessoa', 'Pessoa'), ('documento', 'Documento'), ('veiculo', 'Veículo')], db_index=True, max_length=20)),
                ('objeto_id', models.PositiveBigIntegerField(db_index=True)),
                ('objeto_descricao', models.CharField(blank=True, max_length=255)),
                ('acao', models.CharField(choices=[('criado', 'Criação'), ('alterado', 'Alteração'), ('desativado', 'Desativação'), ('reativado', 'Reativação'), ('excluido', 'Exclusão')], db_index=True, max_length=20)),
                ('alteracoes', models.JSONField(blank=True, default=dict)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['entidade', 'objeto_id', '-criado_em'], name='core_audite_entidad_af980c_idx')],
            },
        ),
    ]
