FROM python:3.12-slim
RUN apt-get update && \
    apt-get install -y p7zip-full locales && \
    locale-gen en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
