# Generated by Django 5.2.9 on 2025-12-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('visitante', 'Visitante'), ('funcionario', 'Funcionário'), ('motorista', 'Motorista')], max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('validade', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pessoas.pessoa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.tipodocumento')),
            ],
        ),
    ]
