# Generated by Django 5.2.9 on 2025-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero'), name='unique_tipo_numero_documento'),
        ),
    ]
