# Generated by Django 6.0 on 2026-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_grupovisita_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupovisita',
            name='is_coleta',
            field=models.BooleanField(default=False),
        ),
    ]
